ami             = "ami-056ee704806822732"
instance_type   = "t2.micro"
Name            =  "Worldpress"
Env             = "Dev"
Created_by      =  "D"
Dept            = "IT"
user_data        = "userdate.sh"